-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 15:23:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema efashion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema efashion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `efashion` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`administrator` (
  `IdAdministratora` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `id_administratora` INT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IdAdministratora`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`artikal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`artikal` (
  `IdArtikla` INT NOT NULL AUTO_INCREMENT,
  `Velicina` VARCHAR(45) NOT NULL,
  `ADMINISTRATOR_IdAdministratora` INT NOT NULL,
  `id_artikla` INT NOT NULL,
  `administrator_id_administratora` INT NOT NULL,
  `Naziv` VARCHAR(255) NOT NULL,
  `Kolicina` INT NOT NULL,
  `Slika` VARCHAR(255) NOT NULL,
  `JedCijena` DECIMAL(6,2) NOT NULL,
  `Boja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdArtikla`, `Velicina`, `Boja`),
  INDEX `fk_ARTIKAL_ADMINISTRATOR_idx` (`ADMINISTRATOR_IdAdministratora` ASC) VISIBLE,
  CONSTRAINT `fk_ARTIKAL_ADMINISTRATOR`
    FOREIGN KEY (`ADMINISTRATOR_IdAdministratora`)
    REFERENCES `test`.`administrator` (`IdAdministratora`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`mjesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`mjesto` (
  `PostanskiBroj` INT NOT NULL,
  `Naziv` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PostanskiBroj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`kupac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`kupac` (
  `IdKupca` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NULL DEFAULT NULL,
  `id_kupca` INT NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Ime` VARCHAR(255) NOT NULL,
  `Prezime` VARCHAR(255) NOT NULL,
  `Adresa` VARCHAR(255) NOT NULL,
  `BrojTelefona` VARCHAR(255) NOT NULL,
  `MJESTO_PostanskiBroj` INT NOT NULL,
  PRIMARY KEY (`IdKupca`),
  INDEX `fk_KUPAC_MJESTO_idx` (`MJESTO_PostanskiBroj` ASC) VISIBLE,
  CONSTRAINT `fk_KUPAC_MJESTO`
    FOREIGN KEY (`MJESTO_PostanskiBroj`)
    REFERENCES `test`.`mjesto` (`PostanskiBroj`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`narudzba` (
  `IdNarudzbe` INT NOT NULL AUTO_INCREMENT,
  `UkupnaCijena` DECIMAL(6,2) NOT NULL,
  `Datum` DATE NOT NULL,
  `ADMINISTRATOR_IdAdministratora` INT NULL DEFAULT NULL,
  `id_narudzbe` INT NOT NULL,
  `ukupna_cijena` DECIMAL(2,0) NOT NULL,
  `administrator_id_administratora` INT NULL DEFAULT NULL,
  `Adresa` VARCHAR(255) NOT NULL,
  `Ime` VARCHAR(255) NOT NULL,
  `Prezime` VARCHAR(255) NOT NULL,
  `BrojTelefona` VARCHAR(255) NOT NULL,
  `Isporuceno` TINYINT NOT NULL,
  `MJESTO_PostanskiBroj` INT NOT NULL,
  PRIMARY KEY (`IdNarudzbe`),
  INDEX `fk_NARUDZBA_ADMINISTRATOR1_idx` (`ADMINISTRATOR_IdAdministratora` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_MJESTO_idx` (`MJESTO_PostanskiBroj` ASC) VISIBLE,
  CONSTRAINT `fk_NARUDZBA_ADMINISTRATOR1`
    FOREIGN KEY (`ADMINISTRATOR_IdAdministratora`)
    REFERENCES `test`.`administrator` (`IdAdministratora`),
  CONSTRAINT `fk_NARUDZBA_MJESTO`
    FOREIGN KEY (`MJESTO_PostanskiBroj`)
    REFERENCES `test`.`mjesto` (`PostanskiBroj`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`potvrda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`potvrda` (
  `IdPotvrde` INT NOT NULL AUTO_INCREMENT,
  `ProslaNarudzba` TINYINT NOT NULL,
  `Datum` DATE NOT NULL,
  `NARUDZBA_IdNarudzbe` INT NOT NULL,
  PRIMARY KEY (`IdPotvrde`, `NARUDZBA_IdNarudzbe`),
  INDEX `fk_POTVRDA_NARUDZBA1_idx` (`NARUDZBA_IdNarudzbe` ASC) VISIBLE,
  CONSTRAINT `fk_POTVRDA_NARUDZBA1`
    FOREIGN KEY (`NARUDZBA_IdNarudzbe`)
    REFERENCES `test`.`narudzba` (`IdNarudzbe`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`stavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`stavka` (
  `ARTIKAL_IdArtikla` INT NOT NULL,
  `NARUDZBA_IdNarudzbe` INT NOT NULL,
  `narudzba_id_narudzbe` INT NOT NULL,
  `artikal_id_artikla` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  `Cijena` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`ARTIKAL_IdArtikla`, `NARUDZBA_IdNarudzbe`),
  INDEX `fk_ARTIKAL_has_NARUDZBA_NARUDZBA1_idx` (`NARUDZBA_IdNarudzbe` ASC) VISIBLE,
  INDEX `fk_ARTIKAL_has_NARUDZBA_ARTIKAL1_idx` (`ARTIKAL_IdArtikla` ASC) VISIBLE,
  CONSTRAINT `fk_ARTIKAL_has_NARUDZBA_ARTIKAL1`
    FOREIGN KEY (`ARTIKAL_IdArtikla`)
    REFERENCES `test`.`artikal` (`IdArtikla`),
  CONSTRAINT `fk_ARTIKAL_has_NARUDZBA_NARUDZBA1`
    FOREIGN KEY (`NARUDZBA_IdNarudzbe`)
    REFERENCES `test`.`narudzba` (`IdNarudzbe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `efashion` ;

-- -----------------------------------------------------
-- Table `efashion`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`administrator` (
  `idadministratora` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idadministratora`),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`artikal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`artikal` (
  `idartikla` INT NOT NULL AUTO_INCREMENT,
  `velicina` VARCHAR(45) NOT NULL,
  `naziv` VARCHAR(255) NOT NULL,
  `kolicina` INT NOT NULL,
  `slika` VARCHAR(255) NULL DEFAULT NULL,
  `jedcijena` DECIMAL(6,2) NOT NULL,
  `idadministratora` INT NOT NULL,
  PRIMARY KEY (`idartikla`, `velicina`),
  INDEX `fk_ARTIKAL_ADMINISTRATOR1_idx` (`idadministratora` ASC) VISIBLE,
  CONSTRAINT `fk_ARTIKAL_ADMINISTRATOR1`
    FOREIGN KEY (`idadministratora`)
    REFERENCES `efashion`.`administrator` (`idadministratora`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`mjesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`mjesto` (
  `postanskibroj` INT NOT NULL,
  `naziv` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`postanskibroj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`kupac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`kupac` (
  `idkupca` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `ime` VARCHAR(255) NOT NULL,
  `prezime` VARCHAR(255) NOT NULL,
  `adresa` VARCHAR(255) NOT NULL,
  `brojtelefona` VARCHAR(50) NOT NULL,
  `postanskibroj` INT NOT NULL,
  PRIMARY KEY (`idkupca`),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_KUPAC_MJESTO1_idx` (`postanskibroj` ASC) VISIBLE,
  CONSTRAINT `fk_KUPAC_MJESTO1`
    FOREIGN KEY (`postanskibroj`)
    REFERENCES `efashion`.`mjesto` (`postanskibroj`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`narudzba` (
  `idnarudzbe` INT NOT NULL AUTO_INCREMENT,
  `ukupnacijena` DECIMAL(7,2) NOT NULL,
  `datum` DATE NOT NULL,
  `adresa` VARCHAR(255) NOT NULL,
  `ime` VARCHAR(255) NOT NULL,
  `prezime` VARCHAR(255) NOT NULL,
  `brojtelefona` VARCHAR(50) NOT NULL,
  `isporuceno` TINYINT NOT NULL,
  `idadministratora` INT NULL DEFAULT NULL,
  `postanskibroj` INT NOT NULL,
  `idkupca` INT NOT NULL,
  PRIMARY KEY (`idnarudzbe`),
  INDEX `fk_NARUDZBA_ADMINISTRATOR1_idx` (`idadministratora` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_MJESTO1_idx` (`postanskibroj` ASC) VISIBLE,
  INDEX `fk_narudzba_kupac1_idx` (`idkupca` ASC) VISIBLE,
  CONSTRAINT `fk_NARUDZBA_ADMINISTRATOR1`
    FOREIGN KEY (`idadministratora`)
    REFERENCES `efashion`.`administrator` (`idadministratora`),
  CONSTRAINT `fk_narudzba_kupac1`
    FOREIGN KEY (`idkupca`)
    REFERENCES `efashion`.`kupac` (`idkupca`),
  CONSTRAINT `fk_NARUDZBA_MJESTO1`
    FOREIGN KEY (`postanskibroj`)
    REFERENCES `efashion`.`mjesto` (`postanskibroj`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`potvrda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`potvrda` (
  `idpotvrde` INT NOT NULL AUTO_INCREMENT,
  `proslanarudzba` TINYINT NOT NULL,
  `datumobrade` DATE NOT NULL,
  `idnarudzbe` INT NOT NULL,
  PRIMARY KEY (`idpotvrde`),
  INDEX `fk_potvrda_narudzba1_idx` (`idnarudzbe` ASC) VISIBLE,
  CONSTRAINT `fk_potvrda_narudzba1`
    FOREIGN KEY (`idnarudzbe`)
    REFERENCES `efashion`.`narudzba` (`idnarudzbe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `efashion`.`stavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efashion`.`stavka` (
  `idartikla` INT NOT NULL,
  `velicina` VARCHAR(45) NOT NULL,
  `idnarudzbe` INT NOT NULL,
  `kolicina` INT NOT NULL,
  `cijena` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idartikla`, `velicina`, `idnarudzbe`),
  INDEX `fk_KUPAC_has_ARTIKAL_ARTIKAL1_idx` (`idartikla` ASC, `velicina` ASC) VISIBLE,
  INDEX `fk_STAVKA_NARUDZBA1_idx` (`idnarudzbe` ASC) VISIBLE,
  CONSTRAINT `fk_KUPAC_has_ARTIKAL_ARTIKAL1`
    FOREIGN KEY (`idartikla` , `velicina`)
    REFERENCES `efashion`.`artikal` (`idartikla` , `velicina`),
  CONSTRAINT `fk_STAVKA_NARUDZBA1`
    FOREIGN KEY (`idnarudzbe`)
    REFERENCES `efashion`.`narudzba` (`idnarudzbe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
